// Mocks generated by Mockito 5.4.4 from annotations
// in kaal_spinnex/test/unit/repositories/question_repository_test.dart.
// DO NOT EDIT manually — normally generated by build_runner.

import 'package:mockito/mockito.dart';
import 'package:kaal_spinnex/data/models/question_model.dart';
import 'package:kaal_spinnex/data/providers/question_provider.dart';

class MockQuestionProvider extends Mock implements QuestionProvider {
  @override
  Future<List<Question>> fetchQuestions(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#fetchQuestions, [category]),
            returnValue: Future.value(<Question>[]),
            returnValueForMissingStub: Future.value(<Question>[]),
          )
          as Future<List<Question>>);
}
