// Mocks generated by Mockito 5.4.4 from annotations
// in kaal_spinnex/test/unit/controllers/home_controller_test.dart.
// DO NOT EDIT manually — normally generated by build_runner.

import 'package:mockito/mockito.dart';
import 'package:kaal_spinnex/data/models/question_model.dart';
import 'package:kaal_spinnex/data/repositories/question_repository.dart';

class MockQuestionRepository extends Mock implements QuestionRepository {
  @override
  Future<List<Question>> getQuestions(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [category]),
            returnValue: Future.value(<Question>[]),
            returnValueForMissingStub: Future.value(<Question>[]),
          )
          as Future<List<Question>>);
}
